server:
  port: 9966
  base-path: /offer-integration-template
  error:
    include-message: always
logging:
  config: config/log4j2.xml
  appender: logFile
spring:
  datasource:
    url: jdbc:postgresql://172.16.16.24:5432/evamdb
    username: evam
    password: evamdb@1234!
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 45000
      validation-timeout: 7500
      idle-timeout: 1200000
      max-lifetime: 2700000
      data-source-properties:
        implicitCachingEnabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: true
        order_inserts: true
        order_updates: true
        use_sql_comments: false
        show_sql: false
kafka:
  bootstrap-address: 172.16.16.19:9092,172.16.16.20:9092,172.16.16.21:9092
  event-topic:
    name: campaignEventsTopic
    partition: 8
    replication: 1
    retention-ms: 43200000
  integration-topic:
    name: verifyVAS
    group: verifyVASGroup
    auto-offset-reset: earliest
    enable-auto-commit: false
    partition: 6
    replication: 3
    retention-ms: 21600000
    concurrency: 4
    max-pool-records: 1000
  producer:
    buffer-memory: 33554432
    batch-size: 16384
    linger-ms: 300
    acks: 1
### RATE LIMITER
#### The client send method is called a maximum of 5 times in 1 second.
resilience4j.ratelimiter:
  instances:
    client-limiter:
      limitForPeriod: 5
      limitRefreshPeriod: 1s
custom-offer-event-name:
  fail: boltonVerificationFail
  success: boltonVerificationSuccess
vas:
  # possible values of phase are profile|verify|action
  phase: verify
  timeRestricted: false
  silentModeStart: '19:59:59'
  silentModeEnd: '09:00:01'
  persist:
    enabled: true
    jobBufferSize: 5000
    poolSize: 2
    sql:
      action:
      profile:
      verify: >-
        INSERT INTO evam.ptcl_bolton_verification (
          debug_mode, part_number, virtual_number, action, response_code, response_description, 
          response_integrationId, response_installed_vas, response_xml
        ) 
        VALUES (
          ?, ?, ?, ?, ?, ?, ?, ?, ?
        )
  endpoints:
    action:
    profile:
    verify: http://esb-prd1.ptclgroup.com:7855/BoltonVerification?wsdl
  expr:
    action:
    profile:
    verify:
      code: //Envelope/Body/BoltonVerificationResponse/returnCode
      desc: //Envelope/Body/BoltonVerificationResponse/returnDesc
      integrationId: //Envelope/Body/BoltonVerificationResponse/IntegrationId
      vasList: //Envelope/Body/BoltonVerificationResponse/installedVasList
  payload:
    action:
    profile:
    verify: >-
      <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:bol="http://www.ptcl.net.pk/BoltonVerification/">
        <soapenv:Header/>
        <soapenv:Body>
          <bol:BoltonVerificationRequest>
            <bol:securityParam>
              <bol:username>IIB</bol:username>
              <bol:password>IIB</bol:password>
            </bol:securityParam>
            <bol:boltonPartNumber>:partNumber</bol:boltonPartNumber>
            <bol:serviceId>:virtualNumber</bol:serviceId>
            <bol:action>:actionType</bol:action>
          </bol:BoltonVerificationRequest>
        </soapenv:Body>
      </soapenv:Envelope>
